name: Build Mac OSX (amd64) Executable

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        echo "/Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/Home/bin/" >> $GITHUB_PATH
        echo "GRAALVM_HOME=/Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/Home/" >> $GITHUB_ENV
        mvn package
    - name: Misc
      if: always()
      run: |
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/Home/
        ls -l /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/Home/bin/
        /Users/runner/work/hedgehog/hedgehog/native-image/target/untarred/graalvm-ce-java17-22.3.0/Contents/Home/bin/gu
        gu
    - name: Output artifact
      uses: actions/upload-artifact@v3
      with:
        name: OSX Native Binary
        path: native-image/target/hedgehog.bin
    - name: Run Binary
      run: native-image/target/hedgehog.bin
